/**
 * districts.ts — single-member seats, and the drawing of their boundaries.
 *
 * Proportional counting only needs regions. Everything else — first past the
 * post, preferential, two-round — needs districts, because those systems ask
 * who won *here*, not who won overall.
 *
 * Districts are generated by splitting a region's electorate, and the split is
 * conservative: the total weight of every segment across a region's districts
 * always equals the region's own. That property is what makes redrawing
 * boundaries meaningful rather than magical. A gerrymander cannot create a
 * single voter; it can only decide which district they wake up in.
 */

import { DISTRICT_SORTING } from '../balance.ts';
import type { SegmentKey } from '../content/segments.ts';
import { segmentTemplate } from '../content/segments.ts';
import { affinity, clampIdeology } from '../ideology.ts';
import type { Ideology, Region } from '../types.ts';
import type { Rng } from '../rng.ts';

export interface District {
  id: string;
  regionId: string;
  name: string;
  /** Segment weights for this district alone. */
  composition: Partial<Record<SegmentKey, number>>;
  /**
   * How far this district has been pushed from a neutral split, 0–1.
   * Rises when boundaries are redrawn for advantage and never falls on its own.
   */
  distortion: number;
}

/** Ordinal names, so districts read as places rather than array indices. */
const ORDINALS = [
  'North',
  'South',
  'East',
  'West',
  'Central',
  'Upper',
  'Lower',
  'Inner',
  'Outer',
  'Mid',
  'Far',
  'Old',
  'New',
  'Great',
  'Little',
  'Upper Vale',
  'Lower Vale',
  'Ridge',
  'Hollow',
  'Reach',
  'Moorside',
  'Waterside',
  'Hillside',
  'Marsh',
  'Common',
  'Fields',
  'Heath',
  'Wold',
  'Bridge',
  'Cross',
];

/**
 * Split a region into one district per seat.
 *
 * Each district gets the region's mix, nudged by seeded noise so that
 * neighbouring seats are not identical, then rescaled so the region's totals
 * are preserved exactly.
 */
export function buildDistricts(region: Region, rng: Rng, districtCount?: number): District[] {
  const count = Math.max(1, districtCount ?? region.seats);
  const entries = Object.entries(region.composition ?? {}) as [SegmentKey, number][];

  const districts: District[] = Array.from({ length: count }, (_, index) => ({
    id: `${region.id}-${index + 1}`,
    regionId: region.id,
    name: `${region.name} ${ORDINALS[index % ORDINALS.length]}`,
    composition: {},
    distortion: 0,
  }));

  /*
   * Give each district a character of its own, scattered around the region's
   * centre of gravity. Segments then concentrate where they fit — which is how
   * two seats in the same region end up voting nothing alike.
   */
  const characters: Ideology[] = districts.map(() => ({
    economic: clampIdeology(region.lean.economic + rng.range(-0.55, 0.55)),
    social: clampIdeology(region.lean.social + rng.range(-0.55, 0.55)),
    environmental: clampIdeology(region.lean.environmental + rng.range(-0.55, 0.55)),
  }));

  for (const [segment, total] of entries) {
    if (!total) continue;
    const position = segmentTemplate(segment).ideology;

    /*
     * Weight by fit to each district's character, with a little noise so the
     * sorting is strong but not mechanical.
     */
    const draws = characters.map(
      (character) =>
        Math.exp(affinity(position, character) * DISTRICT_SORTING) * rng.range(0.85, 1.15),
    );
    const drawTotal = draws.reduce((a, b) => a + b, 0);

    /* Rescaling to the region's total is what conserves the electorate. */
    districts.forEach((district, index) => {
      district.composition[segment] = (total * draws[index]!) / drawTotal;
    });
  }

  return districts;
}

/** Total weight of each segment across a set of districts. */
export function segmentTotals(
  districts: readonly District[],
): Partial<Record<SegmentKey, number>> {
  const totals: Partial<Record<SegmentKey, number>> = {};
  for (const district of districts) {
    for (const [segment, weight] of Object.entries(district.composition) as [
      SegmentKey,
      number,
    ][]) {
      totals[segment] = (totals[segment] ?? 0) + weight;
    }
  }
  return totals;
}

/**
 * How friendly a district is to a given position, as a weighted mean of the
 * affinity between that position and each segment living there.
 */
export function districtFavourability(district: District, ideology: Ideology): number {
  let weighted = 0;
  let total = 0;
  for (const [segment, weight] of Object.entries(district.composition) as [
    SegmentKey,
    number,
  ][]) {
    if (!weight) continue;
    weighted += affinity(ideology, segmentTemplate(segment).ideology) * weight;
    total += weight;
  }
  return total > 0 ? weighted / total : 0;
}

export interface RedrawResult {
  districts: District[];
  /** Mean distortion added across the region, 0–1. */
  distortionAdded: number;
  /** Districts conceded outright so that others become winnable. */
  packed: string[];
  /** Districts made more competitive for the beneficiary. */
  cracked: string[];
}

/**
 * Redraw a region's boundaries to favour one position.
 *
 * The two classic moves, both implemented literally:
 *
 *   PACK   — concentrate hostile voters into a small number of districts the
 *            beneficiary was going to lose anyway, so those votes are spent
 *            winning one seat by an enormous margin instead of threatening
 *            several.
 *   CRACK  — spread friendly voters out of safe districts into marginal ones,
 *            trading a wasted majority for extra competitive seats.
 *
 * `intensity` (0–1) is how aggressively to do it. Segment totals across the
 * region are conserved exactly, so this only ever moves voters between
 * districts — it never invents them.
 */
export function redrawBoundaries(
  districts: readonly District[],
  ideology: Ideology,
  intensity: number,
): RedrawResult {
  if (districts.length < 2) {
    return { districts: districts.map((d) => ({ ...d })), distortionAdded: 0, packed: [], cracked: [] };
  }

  const strength = Math.max(0, Math.min(1, intensity));
  const working = districts.map((d) => ({ ...d, composition: { ...d.composition } }));

  const ranked = [...working].sort(
    (a, b) => districtFavourability(a, ideology) - districtFavourability(b, ideology),
  );

  /* The least friendly district absorbs hostile voters; it is conceded. */
  const sink = ranked[0]!;
  /* The safest district can afford to give friendly voters away. */
  const source = ranked[ranked.length - 1]!;
  /* Everything between them is where seats are actually won. */
  const marginals = ranked.slice(1, -1);

  if (marginals.length === 0) {
    return { districts: working, distortionAdded: 0, packed: [], cracked: [] };
  }

  const segments = new Set<SegmentKey>();
  for (const district of working) {
    for (const key of Object.keys(district.composition) as SegmentKey[]) segments.add(key);
  }

  /*
   * Friendly and hostile are RELATIVE, not absolute.
   *
   * Measuring each segment's affinity against zero does not work: on a scale
   * calibrated to the positions parties actually occupy, a centre-left party
   * has mildly positive affinity with almost everyone, so nearly every segment
   * would count as friendly and there would be nothing to pack. What matters
   * to a map-drawer is which voters are better than their average, so the
   * split is taken against the median segment present.
   */
  const affinities = new Map<SegmentKey, number>();
  for (const segment of segments) {
    affinities.set(segment, affinity(ideology, segmentTemplate(segment).ideology));
  }
  const sorted = [...affinities.values()].sort((a, b) => a - b);
  const median =
    sorted.length % 2 === 1
      ? sorted[(sorted.length - 1) / 2]!
      : (sorted[sorted.length / 2 - 1]! + sorted[sorted.length / 2]!) / 2;

  /*
   * Packing has to beat the sink's own average, not merely the region's.
   * The conceded district is already the most hostile one, so moving in voters
   * who are below the regional median but above that district's average makes
   * it LESS hostile — the opposite of packing. Only voters more hostile than
   * the sink already is actually concentrate the opposition there.
   */
  const sinkMean = districtFavourability(sink, ideology);

  for (const segment of segments) {
    const value = affinities.get(segment) ?? 0;
    const friendly = value > median;
    if (!friendly && value >= sinkMean) continue;

    if (friendly) {
      /* CRACK: move friendly voters out of the safe seat into the marginals. */
      const available = source.composition[segment] ?? 0;
      const moved = available * strength * 0.7;
      if (moved <= 0) continue;
      source.composition[segment] = available - moved;
      const perMarginal = moved / marginals.length;
      for (const district of marginals) {
        district.composition[segment] = (district.composition[segment] ?? 0) + perMarginal;
      }
    } else {
      /* PACK: move hostile voters out of the marginals into the conceded seat. */
      let collected = 0;
      for (const district of marginals) {
        const available = district.composition[segment] ?? 0;
        const moved = available * strength * 0.7;
        if (moved <= 0) continue;
        district.composition[segment] = available - moved;
        collected += moved;
      }
      if (collected > 0) {
        sink.composition[segment] = (sink.composition[segment] ?? 0) + collected;
      }
    }
  }

  const added = strength * 0.45;
  for (const district of working) {
    district.distortion = Math.min(1, district.distortion + added);
  }

  return {
    districts: working,
    distortionAdded: added,
    packed: [sink.id],
    cracked: marginals.map((d) => d.id),
  };
}

/** Mean distortion across a set of districts, 0–1. */
export function meanDistortion(districts: readonly District[]): number {
  if (districts.length === 0) return 0;
  return districts.reduce((sum, d) => sum + d.distortion, 0) / districts.length;
}
