/**
 * bills.ts — the legislative catalogue.
 *
 * Content rule, enforced by review and by the `tradeoff` field being required:
 * every bill has a real benefit AND a real cost. None is written as obviously
 * correct or obviously foolish, and the ideology vector is a mechanical
 * position, not a verdict. Recognisable policy shapes (carbon pricing, tuition
 * contributions, wage floors) appear in the abstract only — no real programme,
 * jurisdiction, or party is referenced.
 *
 * Effect conventions:
 *   sectorDeltas   one-off health points
 *   fundingDeltas  permanent change to per-turn funding (₡bn)
 *   treasury       one-off cash (negative spends)
 *   revenueDelta   permanent change to per-turn revenue (₡bn)
 *   approval       one-off approval points
 */

import type { BillCategory, BillMagnitude, Effects, Ideology } from '../types.ts';
import { makeIdeology } from '../ideology.ts';

export interface BillTemplate {
  key: string;
  title: string;
  summary: string;
  tradeoff: string;
  category: BillCategory;
  magnitude: BillMagnitude;
  ideology: Ideology;
  effects: Effects;
}

const bill = (
  key: string,
  title: string,
  category: BillCategory,
  magnitude: BillMagnitude,
  ideology: Ideology,
  summary: string,
  tradeoff: string,
  effects: Effects,
): BillTemplate => ({ key, title, category, magnitude, ideology, summary, tradeoff, effects });

export const BILL_TEMPLATES: BillTemplate[] = [
  /* ---------------------------- fiscal ---------------------------- */
  bill(
    'fiscal-graduated-schedule',
    'Graduated Income Schedule',
    'fiscal',
    'major',
    makeIdeology(-0.6, 0.1, 0),
    'Restructures income tax into steeper bands, raising sustained revenue from higher earners.',
    'Durable revenue, but it lands as a visible tax rise and measurably slows private activity.',
    { revenueDelta: 108, approval: -3.5, sectorDeltas: { economy: -3 } },
  ),
  bill(
    'fiscal-consumption-cut',
    'Consumption Tax Reduction',
    'fiscal',
    'major',
    makeIdeology(0.65, 0, -0.1),
    'Cuts the general consumption rate, leaving more money in household hands immediately.',
    'Popular and genuinely stimulative — and it tears a permanent hole in the revenue base.',
    { revenueDelta: -96, approval: 4, sectorDeltas: { economy: 3 } },
  ),
  bill(
    'fiscal-corporate-realignment',
    'Corporate Rate Realignment',
    'fiscal',
    'major',
    makeIdeology(0.55, -0.05, -0.15),
    'Lowers the headline company rate while closing several deductions.',
    'Investment responds well; the net revenue loss is real and the optics are poor.',
    { revenueDelta: -72, sectorDeltas: { economy: 5 }, approval: -1.5 },
  ),
  bill(
    'fiscal-dormant-assets',
    'Dormant Asset Levy',
    'fiscal',
    'minor',
    makeIdeology(-0.35, 0.05, 0),
    'Sweeps long-inactive accounts and unclaimed balances into the treasury.',
    'A useful one-off cheque that can never be written twice, and depositors resent it.',
    { treasury: 14, approval: -1, sectorDeltas: { economy: -1 } },
  ),
  bill(
    'fiscal-refinancing',
    'Debt Refinancing Window',
    'fiscal',
    'minor',
    makeIdeology(0.2, 0, 0),
    'Retires expensive paper early using available cash reserves.',
    'Cuts the interest bill for good, but drains the cash you might need for a crisis.',
    { debt: -25, treasury: -6 },
  ),
  bill(
    'fiscal-consolidation',
    'Consolidation Act',
    'fiscal',
    'major',
    makeIdeology(0.7, -0.1, -0.2),
    'Applies an across-the-board reduction to every departmental allocation.',
    'The fastest route to a balanced budget, paid for in every service at once.',
    {
      fundingDeltas: {
        economy: -36,
        health: -36,
        education: -36,
        infrastructure: -36,
        environment: -36,
      },
      approval: -6,
    },
  ),

  /* ---------------------------- health ---------------------------- */
  bill(
    'health-primary-care',
    'Primary Care Expansion',
    'health',
    'major',
    makeIdeology(-0.5, 0.2, 0),
    'Funds a large increase in front-line general practice capacity.',
    'Visibly shortens waits and is widely welcomed; the higher funding line is permanent.',
    { fundingDeltas: { health: 72 }, sectorDeltas: { health: 6 }, approval: 4 },
  ),
  bill(
    'health-throughput',
    'Hospital Throughput Reform',
    'health',
    'minor',
    makeIdeology(0.3, -0.05, 0),
    'Rewrites scheduling and discharge rules to move patients through faster.',
    'Real capacity gains without new money, at the cost of a bruising fight with staff bodies.',
    { sectorDeltas: { health: 5 }, approval: -2, treasury: -4 },
  ),
  bill(
    'health-bulk-purchasing',
    'Pharmaceutical Bulk Purchasing',
    'health',
    'minor',
    makeIdeology(-0.4, 0, 0),
    'Centralises medicine procurement into a single national buyer.',
    'Cheaper supply and better stock control; suppliers retaliate by narrowing what they list.',
    { sectorDeltas: { health: 3 }, revenueDelta: 24, approval: 1.5 },
  ),
  bill(
    'health-private-capacity',
    'Private Capacity Contracting',
    'health',
    'major',
    makeIdeology(0.65, -0.1, 0),
    'Buys surge capacity from independent providers to clear the backlog.',
    'Clears waiting lists quickly, and hands a permanent claim on the health budget to contractors.',
    { sectorDeltas: { health: 7 }, revenueDelta: -48, approval: -1 },
  ),
  bill(
    'health-preventive-levy',
    'Preventive Health Levy',
    'health',
    'minor',
    makeIdeology(-0.2, 0.3, 0.1),
    'Taxes a narrow category of goods and earmarks the proceeds for prevention.',
    'Raises money and improves long-run outcomes; voters experience it as a tax on daily life.',
    { revenueDelta: 36, sectorDeltas: { health: 2 }, approval: -3.5 },
  ),
  bill(
    'health-rural-clinics',
    'Rural Clinic Guarantee',
    'health',
    'minor',
    makeIdeology(-0.25, -0.2, 0.05),
    'Guarantees a staffed clinic within a fixed travel time of every settlement.',
    'Deeply popular in thin constituencies; the per-patient cost is indefensible on a spreadsheet.',
    { sectorDeltas: { health: 3 }, fundingDeltas: { health: 24 }, approval: 2.5 },
  ),

  /* --------------------------- education -------------------------- */
  bill(
    'education-early-years',
    'Universal Early Years Place',
    'education',
    'major',
    makeIdeology(-0.55, 0.4, 0),
    'Entitles every child to a funded place from an early age.',
    'Strong long-run returns and immediate relief for parents, on a permanently higher budget line.',
    { sectorDeltas: { education: 7 }, fundingDeltas: { education: 60 }, approval: 3.5 },
  ),
  bill(
    'education-vocational',
    'Vocational Pathways Act',
    'education',
    'major',
    makeIdeology(0.2, -0.1, 0),
    'Builds a technical track with employer-backed qualifications.',
    'Feeds skilled labour into the economy within years, after a large upfront build cost.',
    { sectorDeltas: { education: 5, economy: 4 }, approval: 2, treasury: -18 },
  ),
  bill(
    'education-class-size',
    'Class Size Reduction',
    'education',
    'minor',
    makeIdeology(-0.4, 0.15, 0),
    'Caps class sizes in the early years of schooling.',
    'Parents notice it immediately; it requires more rooms and more staff, forever.',
    { sectorDeltas: { education: 4 }, fundingDeltas: { education: 36 }, approval: 2 },
  ),
  bill(
    'education-curriculum',
    'Curriculum Standardisation',
    'education',
    'minor',
    makeIdeology(0.1, -0.5, 0),
    'Imposes a common core curriculum and common assessment across all schools.',
    'Raises the floor and makes outcomes comparable; costs schools their local discretion.',
    { sectorDeltas: { education: 3 }, approval: -2 },
  ),
  bill(
    'education-tuition',
    'Tuition Contribution Reform',
    'education',
    'major',
    makeIdeology(0.6, -0.1, 0),
    'Shifts a larger share of tertiary cost onto graduates through income-linked repayment.',
    'Materially improves the fiscal position and materially narrows who applies.',
    { revenueDelta: 60, sectorDeltas: { education: -3 }, approval: -5 },
  ),
  bill(
    'education-retention',
    'Teacher Retention Settlement',
    'education',
    'minor',
    makeIdeology(-0.45, 0.1, 0),
    'Settles the pay dispute and funds retention premiums in shortage subjects.',
    'Ends the disruption and stops the exodus; every other public workforce now has a benchmark.',
    { sectorDeltas: { education: 4 }, fundingDeltas: { education: 24 }, approval: 1.5, treasury: -8 },
  ),

  /* ------------------------- infrastructure ----------------------- */
  bill(
    'infra-rail-renewal',
    'National Rail Renewal',
    'infrastructure',
    'major',
    makeIdeology(-0.3, 0, 0.4),
    'A decade-long reconstruction of the trunk rail network.',
    'Transformative for the regions it reaches, financed almost entirely by new borrowing.',
    { sectorDeltas: { infrastructure: 8, economy: 3 }, debt: 60, approval: 3 },
  ),
  bill(
    'infra-highway-backlog',
    'Highway Maintenance Backlog',
    'infrastructure',
    'minor',
    makeIdeology(0.05, -0.1, -0.1),
    'Clears the accumulated repair backlog on primary roads.',
    'Unglamorous, immediately felt, and pure cash out the door with no lasting asset.',
    { sectorDeltas: { infrastructure: 4 }, treasury: -12 },
  ),
  bill(
    'infra-broadband',
    'Broadband Universal Service',
    'infrastructure',
    'major',
    makeIdeology(-0.2, 0.15, 0),
    'Obliges universal high-capacity connection, subsidised in unprofitable areas.',
    'Lifts the economy and schooling together; the final ten percent of coverage costs the most.',
    { sectorDeltas: { infrastructure: 6, economy: 3, education: 2 }, treasury: -22 },
  ),
  bill(
    'infra-ports',
    'Port Modernisation',
    'infrastructure',
    'minor',
    makeIdeology(0.4, -0.05, -0.2),
    'Automates cargo handling at the three principal ports.',
    'Throughput and trade improve; dredging and dockside works damage the coastal margin.',
    { sectorDeltas: { infrastructure: 4, economy: 3, environment: -2 } },
  ),
  bill(
    'infra-housing',
    'Housing Supply Acceleration',
    'infrastructure',
    'major',
    makeIdeology(0.35, 0.2, -0.25),
    'Overrides local refusal for schemes above a size threshold.',
    'The only fast answer to supply, bought by stripping communities of a veto and building on green land.',
    { sectorDeltas: { infrastructure: 6, environment: -4 }, approval: 3 },
  ),
  bill(
    'infra-water',
    'Water System Overhaul',
    'infrastructure',
    'minor',
    makeIdeology(-0.15, 0, 0.45),
    'Replaces failing mains and ends routine discharge into waterways.',
    'Fixes two problems at once, and the bill arrives in a single unavoidable lump.',
    { sectorDeltas: { infrastructure: 4, environment: 3 }, treasury: -16 },
  ),

  /* -------------------------- environment ------------------------- */
  bill(
    'env-carbon-pricing',
    'Carbon Pricing Framework',
    'environment',
    'major',
    makeIdeology(-0.2, 0.05, 0.8),
    'Prices emissions across industry with a scheduled annual tightening.',
    'Raises real revenue and cuts emissions; energy-intensive regions carry the cost first.',
    { revenueDelta: 84, sectorDeltas: { environment: 7, economy: -4 }, approval: -4 },
  ),
  bill(
    'env-grid',
    'Grid Decarbonisation Programme',
    'environment',
    'major',
    makeIdeology(-0.25, 0.05, 0.75),
    'Rebuilds generation and transmission around low-carbon sources.',
    'A genuine structural fix for emissions and energy security, funded by a very large debt issue.',
    { sectorDeltas: { environment: 8, infrastructure: 3 }, debt: 55 },
  ),
  bill(
    'env-extraction',
    'Extraction Licensing Expansion',
    'environment',
    'major',
    makeIdeology(0.5, -0.15, -0.75),
    'Opens new licensing rounds for domestic resource extraction.',
    'Strong revenue and regional employment, against lasting environmental damage.',
    { revenueDelta: 96, sectorDeltas: { economy: 5, environment: -9 }, approval: -2 },
  ),
  bill(
    'env-watershed',
    'Protected Watershed Act',
    'environment',
    'minor',
    makeIdeology(-0.15, 0, 0.6),
    'Places the upland catchments under permanent protection.',
    'Secures water quality for a generation by closing off land the economy was using.',
    { sectorDeltas: { environment: 5, economy: -2 } },
  ),
  bill(
    'env-retrofit',
    'Household Retrofit Scheme',
    'environment',
    'minor',
    makeIdeology(-0.3, 0.1, 0.5),
    'Subsidises insulation and heating replacement for lower-income households.',
    'Cuts bills and emissions together; the subsidy is expensive per tonne and hard to withdraw.',
    { sectorDeltas: { environment: 3 }, approval: 2, treasury: -14 },
  ),
  bill(
    'env-emissions-standard',
    'Industrial Emissions Standard',
    'environment',
    'minor',
    makeIdeology(-0.3, 0, 0.55),
    'Tightens permitted emissions at the point of production.',
    'Cleaner air quickly, and a compliance cost that falls hardest on marginal plants.',
    { sectorDeltas: { environment: 4, economy: -2.5 } },
  ),

  /* ---------------------------- labour ---------------------------- */
  bill(
    'labour-wage-floor',
    'Wage Floor Uplift',
    'labour',
    'major',
    makeIdeology(-0.7, 0.15, 0),
    'Raises the statutory minimum substantially above the current floor.',
    'Lifts low pay immediately; smaller employers absorb it through hours and headcount.',
    { approval: 5, sectorDeltas: { economy: -3 }, revenueDelta: 12 },
  ),
  bill(
    'labour-bargaining',
    'Collective Bargaining Extension',
    'labour',
    'major',
    makeIdeology(-0.65, 0.3, 0),
    'Extends sector-wide agreements to all firms in covered industries.',
    'Raises the floor across whole sectors and reduces the flexibility firms use to absorb shocks.',
    { approval: 2, sectorDeltas: { economy: -2.5 } },
  ),
  bill(
    'labour-flexibility',
    'Labour Market Flexibility Act',
    'labour',
    'major',
    makeIdeology(0.7, -0.15, 0),
    'Loosens dismissal rules and simplifies contracting.',
    'Hiring and output respond strongly; the people carrying the new risk know exactly who did it.',
    { sectorDeltas: { economy: 6 }, approval: -5 },
  ),
  bill(
    'labour-apprenticeships',
    'Apprenticeship Subsidy',
    'labour',
    'minor',
    makeIdeology(-0.2, -0.05, 0),
    'Pays employers a per-place subsidy for accredited apprenticeships.',
    'Cheap, well-targeted skills policy that a share of employers would have funded anyway.',
    { sectorDeltas: { economy: 2, education: 2 }, treasury: -10 },
  ),
  bill(
    'labour-working-time',
    'Working Time Directive',
    'labour',
    'minor',
    makeIdeology(-0.45, 0.35, 0.05),
    'Caps average weekly hours and mandates rest entitlements.',
    'Popular and defensible on health grounds; measured output per worker falls.',
    { approval: 3, sectorDeltas: { economy: -2 } },
  ),
  bill(
    'labour-pension-age',
    'Pension Age Adjustment',
    'labour',
    'major',
    makeIdeology(0.55, -0.1, 0),
    'Raises the state pension age on a published timetable.',
    'Closes a structural hole in the public finances, at the single highest political price available.',
    { revenueDelta: 72, approval: -7 },
  ),

  /* ----------------------------- civic ---------------------------- */
  bill(
    'civic-electoral-admin',
    'Electoral Administration Act',
    'civic',
    'minor',
    makeIdeology(0, 0.4, 0),
    'Modernises registration and standardises polling administration.',
    'Uncontroversial housekeeping that buys goodwill, and eats floor time you needed elsewhere.',
    { approval: 1.5, politicalCapital: 6 },
  ),
  bill(
    'civic-foi',
    'Freedom of Information Expansion',
    'civic',
    'major',
    makeIdeology(0, 0.7, 0.1),
    'Widens disclosure duties across government and public contractors.',
    'A real trust dividend, paid for with a permanent increase in how much of your time is scrutiny.',
    { approval: 4, politicalCapital: -8 },
  ),
  bill(
    'civic-devolution',
    'Devolution of Regional Budgets',
    'civic',
    'major',
    makeIdeology(0.2, 0.3, 0.05),
    'Transfers substantial spending authority to regional administrations.',
    'Decisions land closer to the people affected; the centre loses both leverage and revenue.',
    { approval: 3, sectorDeltas: { infrastructure: 3 }, revenueDelta: -36 },
  ),
  bill(
    'civic-lobbying',
    'Lobbying Transparency Register',
    'civic',
    'minor',
    makeIdeology(-0.05, 0.5, 0.05),
    'Requires disclosure of paid access to ministers and officials.',
    'Cheap credibility, at the cost of channels your own operation was quietly using.',
    { approval: 2.5, politicalCapital: -4 },
  ),
  bill(
    'civic-service-reorg',
    'Civil Service Reorganisation',
    'civic',
    'minor',
    makeIdeology(0.35, -0.1, 0),
    'Merges overlapping agencies and reduces administrative headcount.',
    'A permanent saving, bought with a year of disruption and a visible round of redundancies.',
    { revenueDelta: 36, approval: -2, politicalCapital: 4 },
  ),
  bill(
    'civic-assembly',
    "Citizens' Assembly on the Constitution",
    'civic',
    'minor',
    makeIdeology(-0.05, 0.6, 0.1),
    'Convenes a randomly selected assembly to report on constitutional reform.',
    'Defuses a fight you cannot win outright, and surrenders control of where it ends up.',
    { approval: 2, politicalCapital: -6 },
  ),

  /* ---------------------------- security -------------------------- */
  bill(
    'security-emergency-powers',
    'Emergency Powers Renewal',
    'security',
    'major',
    makeIdeology(0.1, -0.7, 0),
    'Renews standing emergency authorities for a further period.',
    'Hands the executive real freedom of action, and spends public trust to get it.',
    { politicalCapital: 12, approval: -4 },
  ),
  bill(
    'security-border-processing',
    'Border Processing Overhaul',
    'security',
    'major',
    makeIdeology(0.1, -0.45, 0),
    'Rebuilds entry processing around faster casework and fixed timetables.',
    'Ends the visible backlog that has dominated coverage; the build cost is substantial.',
    { approval: 2, treasury: -20 },
  ),
  bill(
    'security-policing-numbers',
    'Policing Numbers Settlement',
    'security',
    'minor',
    makeIdeology(0.05, -0.4, 0),
    'Funds a multi-year increase in officer numbers.',
    'Reliably popular, and locks in a recurring cost that outlives the reason for it.',
    { approval: 3, revenueDelta: -36 },
  ),
  bill(
    'security-surveillance',
    'Digital Surveillance Authority',
    'security',
    'major',
    makeIdeology(0.1, -0.75, 0),
    'Creates a central authority for bulk data access under warrant.',
    'A genuine capability against organised harm, and a permanent new power over everyone else.',
    { politicalCapital: 10, approval: -6 },
  ),
  bill(
    'security-contingencies',
    'Civil Contingencies Reserve',
    'security',
    'minor',
    makeIdeology(0, -0.2, 0.1),
    'Stands up a standing reserve for flood, fire and supply emergencies.',
    'Shortens every future disaster response, and sits idle and expensive until one arrives.',
    { sectorDeltas: { infrastructure: 2 }, approval: 1, treasury: -12 },
  ),
  bill(
    'security-community-policing',
    'Community Policing Pilot',
    'security',
    'minor',
    makeIdeology(-0.1, 0.25, 0),
    'Funds neighbourhood teams with devolved local priorities.',
    'Trust improves where it runs; it is slower than enforcement and harder to show on a chart.',
    { approval: 2, treasury: -8 },
  ),
];

export const BILL_CATEGORY_LABELS: Record<BillCategory, string> = {
  fiscal: 'Fiscal',
  health: 'Health',
  education: 'Education',
  infrastructure: 'Infrastructure',
  environment: 'Environment',
  labour: 'Labour',
  civic: 'Civic',
  security: 'Security',
};
